dataset_name: my_dataset

data_schema:
  - rosbag_topic: /husky/odom
    output_dir: odom
    output_type: csv
    start_idx: 0
    end_idx: -1
    throttle_rate: 1

  - rosbag_topic: /husky/cmd_vel
    output_dir: control
    output_type: csv
    start_idx: 0
    end_idx: -1
    throttle_rate: 1

  - rosbag_topic: /husky/stereo_left/image_rect_color/compressed
    output_dir: img_stereo_left
    output_type: dir_of_files
    start_idx: 0
    end_idx: -1
    throttle_rate: 1
    extra_params:
      height: 440
      width: 600
      fps: 30

